### ISSUE TITLE
Issue with using Spotify links

### ISSUE THREAD

**Issue by IntensityNetwork** [RafaelSolVargas/Vulkan#30]
I can't seem to use spotify links with the music bot. I get the below error 
![image](https://user-images.githubusercontent.com/84586134/198718493-073078bb-668a-4008-8192-c168cb790383.png)

**Comment by RafaelSolVargas** [comment]
Hi
Are you sure that you are using the latest Vulkan version?
I'm almost sure that this error was fixed in this commit: https://github.com/RafaelSolVargas/Vulkan/commit/10e38a88092a3c835c0b9961a0415246b219bd3e.

Please check if that is the case, if the problem persists please send me the spotify URL that are broking the Bot

**Comment by IntensityNetwork** [comment]
Hi I just downloaded the master and it's working fine, in the 1.5 release it only error'd when you used the prefix command, slash commands worked fine

**Comment by RafaelSolVargas** [comment]
Yes, it's like I said, this error has already been fixed, but I was not released.
I just released a 15.1 version with this fix.
Thanks for the bug report and enjoy this project :)
I am closing this issue as it has been resolved
