### ISSUE TITLE
The bot is spamming messages

### ISSUE THREAD

**Issue by Paillat-dev** [RafaelSolVargas/Vulkan#34]
It looks like that when loop=all is selected, at some point, it starts skipping all songs and sending each song in the queue without stopping, like if the songs were 0 seconds long.
I unforunately haven't any screenshot because I cleared the channel.

**Comment by RafaelSolVargas** [comment]
I'll try to reproduce it locally, any informations about when or how it happens will help a lot

**Comment by Paillat-dev** [comment]
Ok, so here are the setps to reproduce it:

1. In the config file, set `SHOULD_AUTO_DISCONNECT_WHEN_ALONE = False`
2. Play 2 songs ( the ones i played where https://www.youtube.com/watch?v=hgr4b-ve6XU&ab_channel=ArthurSena & https://www.youtube.com/watch?v=h8YZMT94rR4&t=7665s&ab_channel=smugkat )
3. Set Loop = all
4. Wait
5. At some point, the bot will stop playing music and start spamming `🎧 Song playing now` messages, skipping the songs like they were 0 minutes long.

**Comment by RafaelSolVargas** [comment]
How long do you usually wait until the bot gets this behavior?
I've fixed some edge issues I've run into over the past few days, but nothing that seems to be related to your issue, and looking through the code I couldn't find a situation that causes this issue.
Maybe the problem is the music source expires, songs downloaded by the Bot don't actually get downloaded, the Bot just takes a URL to a server and passes that URL to discord to play, as you can see in this code below.

![image](https://user-images.githubusercontent.com/86136313/214618210-f0ee5056-2731-4489-b9be-7e84e9bee95f.png)

Maybe after some time that URL can become invalid and the music actually takes 0 seconds to play.
Can you download the commits I made over the past few days and try to find your error again?

Just for you to better understand how the execution works, look for the PlayerProcess.py file in the Parallelism folders, in this class there are two functions that call each other, __playNext() and __playSong(song)
The second tells Discord to play the song and after finishing the song it calls the __playNext function, this checks if there is another song to be played and calls the __playSong function

**Comment by RafaelSolVargas** [comment]
https://rr1---sn-oxunxg8pjvn-4aol.googlevideo.com/videoplayback?expire=1674758495&ei=_3TSY7C0HYPD8wKyw56YCw&ip=2804%3A14d%3Abaa1%3A8c12%3A2636%3A107b%3Af404%3A2618&id=o-APoUozIQlZIgSbA4mDOMDQAKMzi-bF7v-jNbpCuKRsQf&itag=251&source=youtube&requiressl=yes&mh=Pz&mm=31%2C29&mn=sn-oxunxg8pjvn-4aol%2Csn-bg0eznsy&ms=au%2Crdu&mv=m&mvi=1&pl=48&gcr=br&initcwndbps=1078750&spc=H3gIhlsjDS8x1seE447mrUnFkJvDUpU&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4395259&dur=254.801&lmt=1565941960611701&mt=1674736382&fvip=2&keepalive=yes&fexp=24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIXfnAKt9ghFlPPt4iq5geWr9Wh6E9HjH_roioF2ibzeAiAZriZzkgf_PmZ5JU52RMm-I7VHHVN89Cq8JoW3jvV_dg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPNisP3pvaELL0ogZQf4_0h5NwnO2naFCn9lN4UL0eIKAiBRJrTn_-Nacz7W3ALQ526ahc1opsWn127bgvmxss4fUg%3D%3D

This is an example of a song.source, if you look closely, there's this parameter in the URL ```expire=1674758495```, and if you convert that epoch value to a time, it's closer to 6 hours from now, so I think in 6 hours the Bot won't be able to play the songs, I'm going to try this theory and if it's true, I'm going to fix it.
Also, if you put this URL in your browser, you will hear a song

**Comment by RafaelSolVargas** [comment]
The problem is exactly with this url, i already uploaded a patch to fix this error, in this [commit](https://github.com/RafaelSolVargas/Vulkan/commit/f4e9e46d6d008d924baeec4a255233e86e76a216)

If you got any other problems, don't mind asking

**Comment by Paillat-dev** [comment]
Thanks a lot!
Great jib!
