### ISSUE TITLE
Help command error

### ISSUE THREAD

**Issue by rivai45** [RafaelSolVargas/Vulkan#42]
This is first time I use bot, so sorry if I do something wrong

When I want to see all commands, it says :
![image](https://user-images.githubusercontent.com/110272391/226195803-d2889b8e-9390-4b0a-a80c-c5c71e9dd59a.png)

When I check in terminal, it says :
![image](https://user-images.githubusercontent.com/110272391/226195833-ccbb320a-d06f-451a-8586-39d0360f916c.png)

**Comment by RafaelSolVargas** [comment]
Hi, I tried using the #help command here and it worked.
It looks like your error is related to a network issue with Discord, perhaps your network connection or something like a VPN.
It really has nothing to do with the Bot :(

**Comment by RafaelSolVargas** [comment]
![image](https://user-images.githubusercontent.com/86136313/226199358-376d21a4-3208-4c77-9a93-93f67a589771.png)

Hi, thanks for your issue reporting.
After reading the code i discover that the string returned by ```self.__bot.user.avatar``` could be None, as it's defined by the documentation:
```
Returns an Asset for the avatar the user has.

If the user does not have a traditional avatar, None is returned. If you want the avatar that a user has displayed, consider display_avatar.
```

So i added a verification that check if the string returned is not None before adding the thumbnail, as you can see here: https://github.com/RafaelSolVargas/Vulkan/commit/6c15345eac3d31aee1ce7774a943c535ac26737b

Please download the new version of this project and check if your problem was solved!
