### ISSUE TITLE
[Enhancement] Add custom command

### ISSUE THREAD

**Issue by rivai45** [RafaelSolVargas/Vulkan#63]
Can you make custom command for every command?
For example :
prefix (!)
play = p, pl
stop = s
history = h, hs
volume = vol
remove = rem, r, c, clear
etc...

And btw in python 3.12, there were a lot of errors.. so I had to downgrade to python 3.11..
I hope you update the code so it can run in latest version of python..
But for me it's not the main problem..

**Comment by RafaelSolVargas** [comment]
Hello, let me understand more about what you are asking.
The fact that I added the ```aliases=['p']``` piece of code, which you can see in the line below, allows me to call this play command just by typing:
!p XXXX or !play XXXX instead of !play XXXX

https://github.com/RafaelSolVargas/Vulkan/blob/b3a9920037b790ab83bea3c6377fde0d87ca5e8c/DiscordCogs/MusicCog.py#L49

Do you want me to create more aliases for the commands that you listed?
If that is the case, for sure! 
Do you want to list more cases of aliases?

About the errors in the new version of Python, I can check that later, if you have some screenshots of the error you were getting, I would appreciate it.

**Comment by rivai45** [comment]
Ahh.. Yes... But I hope we can set it from .env, not set it in the code..
But yea, now I know where to make a new aliases

**Comment by rivai45** [comment]
I will close this issue.. I hope in the next update you can add that, so it's more easy to setting in .env
